<?php

namespace LaravelQL\LaravelQL;

use Illuminate\Support\ServiceProvider;

class LaravelQLServiceProvider extends ServiceProvider
{

    public function boot(): void
    {
        $this->loadRoutesFrom(__DIR__.'/../routes/api.php');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
